### ISSUE TITLE
can not configure

### ISSUE THREAD

**Issue by SmilePlz** [osyo-manga/vim-marching#13]
I use: 
imap \<C-o> \<Plug>(marching_start_omni_complete)
imap \<C-i> \<Plug>(marching_force_start_omni_complete)

marching completion start                              
Error detected while processing function marching#complete..marching#clang_command#complete..140..<SNR>87_process..117:
line    4:
E117: Unknown function: vimproc#pgroup_open
Error detected while processing function marching#complete..marching#clang_command#complete..140..<SNR>87_process..117:
line    4:
E15: Invalid expression: vimproc#pgroup_open(self.__reunions_process_base.command . ' ' . args)

I understand that the problem is in me. Please advise how to solve it ...

**Comment by Shougo** [comment]
vim-marching uses vimproc.   You must install it.
https://github.com/Shougo/vimproc.vim

Note: I think vim-marching should check if vimproc exists.

**Comment by osyo-manga** [comment]
Thanks @Shougo .

**Comment by SmilePlz** [comment]
thanks you all.
written in large letters:
Requirement
    Vim plugin
        vimproc.vim
