### ISSUE TITLE
Error detected while processing function marching#check_complete_always..marching#clang_command#update_complete_process

### ISSUE THREAD

**Issue by nikelmwann** [osyo-manga/vim-marching#14]
Every time I hit a key in insert mode, I get this error:
```
Error detected while processing function marching#check_complete_always..marching#clang_command#update_complete_process:
line    2:
E119: Not enough arguments for function: 260
```

It only occurs when I have `let g:marching_enable_refresh_always = 1` in my .vimrc. Also, the `260` on the last line of the error changes between buffers it seems.

If it helps, I'm running vim 7.4.752 on Cygwin.

**Comment by iluuu1994** [comment]
I have the same problem... The plugin looks amazing, I'd really love to use it!

**Comment by osyo-manga** [comment]
Thanks for issues :)
I fixed it, Please update plugin and check.

**Comment by nikelmwann** [comment]
Works perfectly now! Thank you very much.

**Comment by osyo-manga** [comment]
OK, Thanks :)
