### ISSUE TITLE
-- Omni completion (^O^N^P) Pattern not found

### ISSUE THREAD

**Issue by SmilePlz** [osyo-manga/vim-marching#16]
I am so sorry. I do not understand why can not I use the plugin. Please give advice.
clang 3.6.2-r100
vim 7.4.769
http://pastebin.com/TfBW1nCJ settings 
http://pastebin.com/5sFsvU5t debug list
I thought that I was doing something wrong. I have run out of ideas.

**Comment by osyo-manga** [comment]
hmm.
I think because the have spaces in the file name.

**Comment by SmilePlz** [comment]
no spaces and also no сyrillic letters. I follow this example https://camo.githubusercontent.com/6590356f2dc2ab3978051af648ecbc7d6d873dde/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3231343438382f313431393437392f62663463333164362d336663632d313165332d393766622d3932386638303036363931652e676966.
http://pastebin.com/YytNVF2u
line std::str (find), line std::sor (not find)
I am saddened. this should work very simply.

**Comment by osyo-manga** [comment]
`std::str` is working?

**Comment by SmilePlz** [comment]
yep

**Comment by SmilePlz** [comment]
I'm sorry I was wrong. does not work. you know how to solve?

**Comment by SmilePlz** [comment]
I use gentoo and this can be solved by installing libstdc ++. 
thanks for the help
